plugins {
    id 'java'
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.18"
}

group = 'net.sanctuaryhosting'
version = '1.21.8'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT")
    compileOnly 'com.fasterxml.jackson.core:jackson-core:2.20.0-rc1' // to fix vulnerability WS-2022-0468, Score: 7.5
    compileOnly 'net.minidev:json-smart:2.6.0'  // to fix vulnerability CVE-2024-57699, Score: 7.5
    compileOnly 'org.apache.commons:commons-lang3:3.18.0' // to fix vulnerability CVE-2025-48924, Score: 5.3
    paperweightDevelopmentBundle("io.papermc.paper:dev-bundle:1.21.8-R0.1-SNAPSHOT")
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}